// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9717opYUd66ffry2opIMWAPIukQoMObg',
    appId: '1:342680650401:web:192f649669ae310c23e6e0',
    messagingSenderId: '342680650401',
    projectId: 'konjic-discover',
    authDomain: 'konjic-discover.firebaseapp.com',
    databaseURL: 'https://konjic-discover-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'konjic-discover.appspot.com',
    measurementId: 'G-MJLFD1S4RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDC0_-toT7jWECd6QnvieYXYlv9kpN15I',
    appId: '1:342680650401:android:eee246ab2644f09c23e6e0',
    messagingSenderId: '342680650401',
    projectId: 'konjic-discover',
    databaseURL: 'https://konjic-discover-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'konjic-discover.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVUtKxRlJ29e6FTucV_HRiE8E93L5-YeM',
    appId: '1:342680650401:ios:75824127fa2aa6f623e6e0',
    messagingSenderId: '342680650401',
    projectId: 'konjic-discover',
    databaseURL: 'https://konjic-discover-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'konjic-discover.appspot.com',
    iosBundleId: 'ba.sskonjic.discover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVUtKxRlJ29e6FTucV_HRiE8E93L5-YeM',
    appId: '1:342680650401:ios:5e061f16d406b36423e6e0',
    messagingSenderId: '342680650401',
    projectId: 'konjic-discover',
    databaseURL: 'https://konjic-discover-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'konjic-discover.appspot.com',
    iosBundleId: 'ba.sskonjic.discover.RunnerTests',
  );
}
